compliments-settings:
  list:
    - compliment: хороший
    - compliment: добрый
    - compliment: умный
    - compliment: чуткий
    - compliment: веселый
    - compliment: смелый
    - compliment: заботливый
    - compliment: быстрый
    - compliment: великодушный